import "./globals.css";

export const metadata = {
  title: "Sea-Turtles",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-site-gradient bg-no-repeat bg-cover text-white font-secondary">
        {children}
      </body>
    </html>
  );
}
