import "./globals.css";

export const metadata = {
  title: "Sea-Turtles",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-site-gradient min-h-screen text-white font-secondary">
        {children}
      </body>
    </html>
  );
}
